# Generated by Django 4.2.1 on 2024-03-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_description_jobinfo_description_and_more'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizenship',
        ),
    ]
