# Generated by Django 4.2.1 on 2024-03-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='industries.industry'),
            preserve_default=False,
        ),
    ]
