version: '3'

services:

  db:
    container_name: db
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    env_file:
      - .env

  web:
    container_name: web
    build: application_builder
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./application_builder/:/app
    depends_on:
      - db
    restart: always
    env_file:
      - .env


volumes:
  postgres_data:
