version: '3'


services:

  db:
    container_name: db
    image: postgres:13
    ports:
      - 54322:5432
    volumes:
      - pg_data_hr_space:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: 'db'
    restart: always
    env_file:
      - .env

  web:
    container_name: web
    build: application_builder
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./application_builder/:/app
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  front:
    container_name: front
    build: ../hrspace-frontend
    depends_on:
      - web

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 8081:8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - front
    restart: always


volumes:
  pg_data_hr_space:
  static_value:
  media_value:
