# Generated by Django 4.2.1 on 2024-03-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageProficiency',
        ),
    ]
