# Generated by Django 4.2.1 on 2024-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.BigIntegerField()),
                ('payment_type', models.CharField(choices=[('100%_first_day', '100% оплаты рекрутеру в день выхода сотрудника'), ('50%_first_day_50%_warranty_period_expiration', '50% за выход и 50% по окончанию гарантийного периода'), ('100%_warranty_period_expiration', '100% оплаты рекрутеру по окончанию гарантийного периода')])),
            ],
        ),
    ]
