# Generated by Django 4.2.1 on 2024-03-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('100%_first_day', '100% оплаты рекрутеру в день выхода сотрудника'), ('50%_first_day_50%_warranty_period_expiration', '50% за выход и 50% по окончанию гарантийного периода'), ('100%_warranty_period_expiration', '100% оплаты рекрутеру по окончанию гарантийного периода')], max_length=100),
        ),
    ]
