# Generated by Django 4.2.1 on 2024-03-21 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professions', '0001_initial'),
        ('cities', '0001_initial'),
        ('citizenships', '0001_initial'),
        ('industries', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_employees', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('start_working', models.CharField(blank=True, choices=[('tomorrow', 'Сможет приступить завтра'), ('in_week', 'В течение недели'), ('in_month', 'В течение месяца'), ('not_hurry', 'Не спешу с поиском')], max_length=100, null=True)),
                ('number_of_recruiters', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_skills', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Fluent', 'Fluent')], max_length=100, null=True)),
                ('recruiter_responsibilities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('resume_searching', 'Поиск и предоставление релевантных резюме'), ('interview_organizing', 'Организация собеседований с заказчиком, синхронизация по времени заказчика и соискателя'), ('recomendation_request', 'Запрос рекомендаций с предыдущих мест работы'), ('sending_tests', 'Отправка кандидату тестового задания'), ('sending_security_service_form', 'Отправка кандидату анкеты службы безопасности'), ('sending_offer', 'Отправка кандидату приглашения на работу')], max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('candidate_resume_form', models.CharField(blank=True, choices=[('no_pre_interview', 'Резюме без предварительного собеседования'), ('with_pre_interview', 'Резюме кандидатов, с которыми проведено интервью, с комментариями по кандидату')], max_length=100, null=True)),
                ('stop_list', models.TextField(blank=True, max_length=1000, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruit_requirements', to='applications.application')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industries.industry')),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('full-time', 'Полная занятость'), ('part-time', 'Частичная занятость'), ('project', 'Проект'), ('shift_work', 'Вахта'), ('traineeship', 'Стажировка')], max_length=1000, null=True)),
                ('schedule', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('full-day', 'Полный день'), ('part-time', 'Неполный день'), ('5_on_2_off', '5/2'), ('2_on_2_off', 'Два через два'), ('24_h_on_72_h_off', 'Сутки / трое'), ('flexible', 'Свободный'), ('shift_work', 'Вахта')], max_length=1000, null=True)),
                ('work_model', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('office', 'Офис'), ('remote', 'Удаленный'), ('hybrid', 'Гибрид')], max_length=1000, null=True)),
                ('contract_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('contract', 'Трудовой договор'), ('civil-personal_contract', 'ГПХ'), ('individual_entrepreneurship', 'ИП'), ('self-employed', 'Самозанятый'), ('holding_multiple_positions', 'Совместительство')], max_length=1000, null=True)),
                ('working_conditions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VMI', 'ДМС'), ('fitness', 'Фитнес'), ('meal_compensation', 'Оплата питания'), ('free_parking', 'Бесплатная парковка'), ('mobile_phone_compensation', 'Оплата мобильной связи'), ('transportation_compensation', 'Оплата проезда'), ('language_training', 'Языковые курсы'), ('professional_training', 'Профессиональные курсы'), ('from_age_14', 'Подходит подросткам с 14 лет'), ('for_people_with_disabilities', 'Подходит людям с ограниченными возможностями')], max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_infos', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('not_required', 'Не имеет значения'), ('higher', 'Высшее'), ('vocational', 'Среднее профессиональное')], max_length=1000, null=True)),
                ('experience', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('not_required', 'Не имеет значения'), ('no_experience', 'Нет опыта'), ('1-3_years', 'От 1 года до 3 лет'), ('3-6_years', 'От 3 до 6 лет'), ('over_6_years', 'Более 6 лет')], max_length=1000, null=True)),
                ('driving_skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('B', 'Категория B, легковые автомобили'), ('C', 'Категория C, грузовые автомобили'), ('D', 'Категория D, автобусы'), ('M', 'Категория M, мопеды'), ('A', 'Категория A, мотоциклы')], max_length=1000, null=True)),
                ('has_medical_certificate', models.BooleanField(blank=True, default=False, null=True)),
                ('has_photo', models.BooleanField(blank=True, default=False, null=True)),
                ('coreskills_and_responsibilities', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_requirements', to='applications.application')),
                ('citizenship', models.ManyToManyField(blank=True, to='citizenships.citizenship')),
                ('language_skills', models.ManyToManyField(blank=True, to='languages.languageproficiency')),
            ],
        ),
    ]
