# Generated by Django 4.2.1 on 2024-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitrequirements',
            name='expirience',
            field=models.CharField(blank=True, choices=[('no_important', 'Неважно'), ('important', 'Важно')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='start_working',
            field=models.CharField(blank=True, choices=[('tomorrow', 'Сможет приступить завтра'), ('in_week', 'В течение недели'), ('in_month', 'В течение месяца'), ('in_3_month', 'В течение 3 месяцев'), ('not_hurry', 'Не спешу с поиском')], max_length=100, null=True),
        ),
    ]
