# Generated by Django 5.0.3 on 2024-03-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('cities', '0001_initial'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidaterequirements',
            name='citizenship',
            field=models.ManyToManyField(to='cities.citizenship'),
        ),
        migrations.AddField(
            model_name='candidaterequirements',
            name='language_skills',
            field=models.ManyToManyField(to='languages.languageproficiency'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_requirements',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.candidaterequirements'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.jobinfo'),
        ),
    ]
