# Generated by Django 4.2.1 on 2024-03-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobinfo_application'),
        ('applications', '0002_initial'),
    ]

    operations = [
    ]
