# Generated by Django 5.0.3 on 2024-03-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_profession'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
            preserve_default=False,
        ),
    ]
