# Generated by Django 4.2.1 on 2024-03-14 08:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('citizenships', '0001_initial'),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidaterequirements',
            name='citizenship',
            field=models.ManyToManyField(to='citizenships.citizenship'),
        ),
        migrations.AlterField(
            model_name='candidaterequirements',
            name='driving_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('B', 'Категория B, легковые автомобили'), ('C', 'Категория C, грузовые автомобили'), ('D', 'Категория D, автобусы'), ('M', 'Категория M, мопеды'), ('A', 'Категория A, мотоциклы')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidaterequirements',
            name='education',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('not_required', 'Не имеет значения'), ('higher', 'Высшее'), ('vocational', 'Среднее профессиональное')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidaterequirements',
            name='experience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('not_required', 'Не имеет значения'), ('no_experience', 'Нет опыта'), ('1-3_years', 'От 1 года до 3 лет'), ('3-6_years', 'От 3 до 6 лет'), ('over_6_years', 'Более 6 лет')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='contract_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('contract', 'Трудовой договор'), ('civil-personal_contract', 'ГПХ'), ('individual_entrepreneurship', 'ИП'), ('self-employed', 'Самозанятый'), ('holding_multiple_positions', 'Совместительство')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full-day', 'Полный день'), ('part-time', 'Неполный день'), ('5_on_2_off', '5/2'), ('2_on_2_off', 'Два через два'), ('24_h_on_72_h_off', 'Сутки / трое'), ('flexible', 'Свободный'), ('shift_work', 'Вахта')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='working_conditions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('VMI', 'ДМС'), ('fitness', 'Фитнес'), ('meal_compensation', 'Оплата питания'), ('free_parking', 'Бесплатная парковка'), ('mobile_phone_compensation', 'Оплата мобильной связи'), ('transportation_compensation', 'Оплата проезда'), ('language_training', 'Языковые курсы'), ('professional_training', 'Профессиональные курсы'), ('from_age_14', 'Подходит подросткам с 14 лет'), ('for_people_with_disabilities', 'Подходит людям с ограниченными возможностями')], max_length=1000),
        ),
        migrations.CreateModel(
            name='RecruitRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', multiselectfield.db.fields.MultiSelectField(choices=[(500, 'от 500'), (100, 'от 100'), (50, 'от 50'), (10, 'от 10'), (0, 'не имеет значения')], max_length=1000)),
                ('completed_tickets', multiselectfield.db.fields.MultiSelectField(choices=[(500, 'от 500'), (100, 'от 100'), (50, 'от 50'), (10, 'от 10'), (0, 'не имеет значения')], max_length=1000)),
                ('experience', multiselectfield.db.fields.MultiSelectField(choices=[('not_required', 'Не имеет значения'), ('no_experience', 'Нет опыта'), ('1-3_years', 'От 1 года до 3 лет'), ('3-6_years', 'От 3 до 6 лет'), ('over_6_years', 'Более 6 лет')], max_length=1000)),
                ('responding_time', multiselectfield.db.fields.MultiSelectField(choices=[(30, 'в течение 30 мин'), (120, 'в течение 2 часов'), (1440, 'в течение дня')], max_length=1000)),
                ('completing_tickets_speed', multiselectfield.db.fields.MultiSelectField(choices=[('quickly', 'быстро, менее недели'), ('medium', 'средняя, до трех недель'), ('no_matter', 'не имеет значения')], max_length=1000)),
                ('english_skills', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Fluent', 'Fluent')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
        ),
    ]
