# Generated by Django 4.2.1 on 2024-03-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_languageproficiency'),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaterequirements',
            name='language_proficiency_level',
        ),
        migrations.AlterField(
            model_name='candidaterequirements',
            name='language_skills',
            field=models.ManyToManyField(blank=True, to='languages.languageproficiency'),
        ),
    ]
