# Generated by Django 5.0.3 on 2024-03-13 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='number_of_employees',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='start_working',
            field=models.CharField(choices=[('tomorrow', 'Сможет приступить завтра'), ('in_week', 'В течение недели'), ('in_month', 'В течение месяца'), ('not_hurry', 'Не спешу с поиском')], default=1),
            preserve_default=False,
        ),
    ]
