# Generated by Django 4.2.1 on 2024-03-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_merge_0002_alter_jobinfo_application_0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitrequirements',
            old_name='expirience',
            new_name='experience',
        ),
    ]
