# Generated by Django 4.2.1 on 2024-03-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_candidaterequirements_language_proficiency_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitrequirements',
            name='city',
        ),
    ]
