# Generated by Django 4.2.1 on 2024-03-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_recruitrequirements_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidaterequirements',
            old_name='requirements_description',
            new_name='coreskills_and_responsibilities',
        ),
        migrations.RemoveField(
            model_name='candidaterequirements',
            name='core_skills',
        ),
    ]
