# Generated by Django 4.2.1 on 2024-03-14 12:31

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
        ('applications', '0004_rename_salary_application_max_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitrequirements',
            name='candidat_resume_form',
            field=models.CharField(blank=True, choices=[('no_pre_interview', 'Резюме без предварительного собеседования'), ('with_pre_interview', 'Резюме кандидатов, с которыми проведено интервью, с комментариями по кандидату')], null=True),
        ),
        migrations.AddField(
            model_name='recruitrequirements',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recruitrequirements',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='industries.industry'),
        ),
        migrations.AddField(
            model_name='recruitrequirements',
            name='recruiter_responsibilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('resume_searching', 'Поиск и предоставление релевантных резюме'), ('interview_organizing', 'Организация собеседований с заказчиком, синхронизация по времени заказчика и соискателя'), ('recomendation_request', 'Запрос рекомендаций с предыдущих мест работы'), ('sending_tests', 'Отправка кандидату тестового задания'), ('sending_security_service_form', 'Отправка кандидату анкеты службы безопасности'), ('sending_offer', 'Отправка кандидату приглашения на работу')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recruitrequirements',
            name='english_skills',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Fluent', 'Fluent')], null=True),
        ),
    ]
