# Generated by Django 4.2.1 on 2024-03-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_recruitrequirements_candidat_resume_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitrequirements',
            name='stop_list',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
