# Generated by Django 4.2.1 on 2024-03-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_rename_requirements_description_candidaterequirements_coreskills_and_responsibilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidaterequirements',
            old_name='has_medical_sertificate',
            new_name='has_medical_certificate',
        ),
    ]
