# Generated by Django 4.2.1 on 2024-03-14 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_recruitrequirements_stop_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='max_salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='min_salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
