# Generated by Django 4.2.1 on 2024-03-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='start_working',
            field=models.CharField(blank=True, choices=[('tomorrow', 'Сможет приступить завтра'), ('in_week', 'В течение недели'), ('in_month', 'В течение месяца'), ('not_hurry', 'Не спешу с поиском')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='work_model',
            field=models.CharField(blank=True, choices=[('office', 'Офис'), ('remote', 'Удаленный'), ('hybrid', 'Гибрид')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruitrequirements',
            name='candidat_resume_form',
            field=models.CharField(blank=True, choices=[('no_pre_interview', 'Резюме без предварительного собеседования'), ('with_pre_interview', 'Резюме кандидатов, с которыми проведено интервью, с комментариями по кандидату')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruitrequirements',
            name='english_skills',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Fluent', 'Fluent')], max_length=100, null=True),
        ),
    ]
